### ISSUE TITLE
ホームのフィードを改善

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-roadmap#91]
# ToDo
- [x] 一部の人気トピックのフィードを流す
- [x] Zennの人気トピック一覧ページにアクセスできるようにする
- [x] 過去のトレンドを深堀りできるようにする
- [x] サイトに1時間後にアクセスしたときに目新しさがあるようにトレンドの更新頻度を上げる
- [x] Trendingをload moreできるようにする
   - はてぶってなんか見ちゃう感じあるよね。ああいうなんとなくどんどん見ちゃうものにしたい
- [x] サイトに1時間後にアクセスしたときに目新しさがあるようにトレンドの更新頻度を上げる（TrendingからFeaturedにする？）
- [x] ある程度Zennの存在が浸透した判断できる段階で、ホームの「How it works」を消す
- [x] トレンドの並び順について、CSSのgridを見直す（2列目の先頭が2番目に人気の記事に見える）

## ページの改善
- [ ] ForYouというログインユーザー向けのページを作る
   - [ ] フォローユーザーの投稿をまとめる
   - [ ] フォロートピックの投稿をまとめる
   - [ ] フォローユーザーがいない場合はフィルターをかけつつランダムでユーザー一覧を出す
   - [ ] フォロートピックがない場合は人気のトピック一覧を出す
   - [ ] ライブラリへのリンクを貼る

## 完成イメージ

HomeHeader

ーーーーーーーーーーーーーーー
|  Trending  |  ForYou  |  Latest  |
ーーーーーーーーーーーーーーー

#### Trending
- Articles（Tech/Idea）とBooksのリスト
- 人気のトピックをランダムに表示
- Daily/Weekly/AllTime でソート可能に

#### ForYou（ログインユーザーにのみ表示される）
- フォローしているユーザーのArticles/Booksを表示
- フォローしているトピックのArticles/Booksを表示
- Likes一覧やReadingListなどへのリンクを表示

#### Latest
- ArticlesとBooksを新着順に並べる

**Comment by catnose99** [comment]
exploreページをつくった。一旦クローズ
